
// Objective-C API for talking to the following Go packages
//
//	example.com/therm
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Therm_FRAMEWORK_H__
#define __Therm_FRAMEWORK_H__

#include "Therm.objc.h"
#include "Universe.objc.h"

#endif
