// Objective-C API for talking to example.com/therm Go package.
//   gobind -lang=objc example.com/therm
//
// File is generated by gobind. Do not edit.

#ifndef __Therm_H__
#define __Therm_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void ThermStartWeb(NSString* _Nullable sensorhost, long sensorport);

FOUNDATION_EXPORT NSString* _Nonnull ThermTherm(NSString* _Nullable name);

#endif
